
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[307] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  115,  113,    5,    6,   79,   42,  113,   41,
       83,   84,   69,   67,   90,   68,   81,   70,   92,   92,
       91,   89,   63,   71,   65,  112,  112,   87,   88,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,   85,  113,   86,   82,    4,    3,    2,
        4,  103,  104,   43,   57,   59,  114,   44,   58,   60,
      106,  107,  114,    5,   62,   77,   74,   72,   73,   80,
       99,  105,  102,   75,    0,   94,   95,    0,    0,   97,
      101,    0,    0,   92,    0,   64,   61,   66,    0,  111,

      112,  112,  112,  112,  112,  112,  112,  112,  112,   16,
      112,  112,  112,  112,  112,   11,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
       78,   76,    3,    0,   43,   52,   51,   56,   54,   53,
       45,   46,   47,   48,   49,   50,    0,   44,  106,  107,
      109,  108,    0,  110,   99,    0,   99,    0,   97,   93,
        0,   97,   96,    0,   92,   38,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,   18,    7,
       22,  112,  112,  112,  112,  112,  112,   35,  112,  112,
      112,  112,  112,  112,  112,  112,    0,   56,   55,    0,

       99,   97,    0,   97,   98,    0,    0,   97,   97,  100,
        0,    0,    0,    0,   10,  112,   14,    8,  112,  112,
      112,  112,   12,   36,  112,  112,  112,   37,  112,  112,
      112,  112,   30,  112,  112,  112,  112,   34,   39,   21,
      112,    0,   56,   55,   99,    0,    0,   97,   98,   93,
      100,   96,   98,    0,  100,   24,   25,  112,  112,  112,
       40,   28,  112,  112,  112,  112,  112,  112,  112,   26,
      112,   17,    0,   97,    0,    0,  112,  112,   29,  112,
      112,  112,  112,   32,   20,    9,   13,    0,   98,    0,
       98,  112,   15,   19,  112,   31,  112,    0,   23,   27,

      112,    0,    0,    1,   33,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   33,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   34,   31,   31,
       35,   36,   37,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       31,   31,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    5,    6,    1,
        7,    1,    1,    1,    1,    1,    8,    8,    8,    8,
        9,    1,    1,    1,    1,    1,   10,   10,   10,   10,
        2,    2,    2,    2,    1,   11,    1,    2,   10,   10,
       10,   10,   10,   10,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        9,    1,    1,    1
    } ;

static const flex_int16_t yy_base[323] =
    {   0,
        0,    0,   63,   66,  221,  219,   69,   70,   74,   75,
       68,   77,  206, 1362,   82, 1362,  174, 1362,  189, 1362,
     1362, 1362,  166,  164, 1362,  158,   72,   84,   97,  143,
     1362, 1362,  156,  150,  142,   94,  130, 1362, 1362,  141,
      145,  162,  119,  150,  174,  176,  198,  201,  206,  214,
      218,  226,  121, 1362,   89, 1362,  125, 1362,   97, 1362,
       96, 1362, 1362,    0, 1362, 1362,  273,    0, 1362, 1362,
      139, 1362,   82,  116, 1362, 1362, 1362, 1362, 1362, 1362,
      317, 1362, 1362, 1362,  219,  206,  194,  138,  233, 1362,
     1362,    0,  224,    0,  242, 1362, 1362, 1362,  265, 1362,

      273,  285,  293,  295,  298,  303,  312,  317,  341,  354,
      362,  367,  370,  375,  372,  380,  384,  388,  392,  396,
      401,  404,  406,  419,  427,  429,  440,  449,  452,  454,
     1362, 1362,  132,   99,    0, 1362, 1362,  213, 1362, 1362,
     1362, 1362, 1362, 1362, 1362, 1362,    0,    0,  116, 1362,
     1362, 1362,  300, 1362,    0,  452, 1362,  266,  490,  450,
      464,  494,   75,  529,  477,  476,  514,  527,  548,  551,
      553,  489,  562,  566,  574,  577,  579,  587,  590,  595,
      600,  609,  611,  613,  621,  626,  629,  634,  637,  639,
      642,  647,  650,  652,  660,  664,   54,  322,    0,  485,

      679,    0,  662, 1362, 1362,  670,  305,  701, 1362, 1362,
      707,    0,  717,  729,  698,  713,  749,  751,  753,  762,
      764,  766,  774,  776,  779,  784,  787,  789,  792,  797,
      801,  809,  811,  814,  822,  825,  830,  839,  848,  850,
      852,   47, 1362, 1362,  845,  867,  873,  879,  912,  666,
      916,   56,    0,  883,  949,  867,  879,  911,  903,  916,
      913,  936,  955,  968,  971,  973,  981,  983,  986,  997,
      999, 1001,   79, 1000, 1006, 1023, 1044, 1048, 1052, 1056,
     1061, 1064, 1066, 1069, 1074, 1077, 1079,   72, 1076, 1072,
     1080, 1114, 1124, 1128, 1132, 1136, 1140, 1144, 1149, 1151,

     1153, 1161, 1164, 1362, 1167, 1362, 1225, 1236, 1247, 1258,
     1269, 1279, 1289, 1299, 1309, 1320, 1324, 1327, 1330, 1333,
     1342, 1351
    } ;

static const flex_int16_t yy_def[323] =
    {   0,
      306,    1,  307,  307,  308,  308,  309,  309,  310,  310,
      311,  311,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  312,  312,  306,  306,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  313,  306,  306,  306,  314,  306,  306,
      315,  306,  316,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,   29,   86,  306,  306,  306,
      306,  317,  306,   30,  306,  306,  306,  306,  306,  306,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      306,  306,  306,  306,  313,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  318,  314,  315,  306,
      306,  306,  316,  306,   81,  306,  306,  306,  306,  306,
      306,  306,  317,  306,  164,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  306,  306,  319,  306,

      306,  159,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  320,  306,  306,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  320,  249,  306,  306,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  306,  306,  306,  306,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  321,  306,  306,
      306,  312,  312,  312,  312,  312,  312,  322,  312,  312,

      312,  306,  322,  306,  312,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306
    } ;

static const flex_int16_t yy_nxt[1427] =
    {   0,
       14,   15,   16,   15,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   30,   30,
       31,   32,   33,   34,   35,   14,   36,   36,   36,   36,
       36,   36,   37,   36,   38,   14,   39,   36,   36,   40,
       41,   42,   43,   44,   36,   36,   45,   36,   36,   36,
       46,   47,   48,   49,   50,   51,   36,   52,   53,   36,
       54,   55,   56,   57,   59,   60,   59,   59,   60,   59,
       72,   65,   65,  288,   66,   66,   69,   69,   73,   72,
      288,   70,   70,   74,  152,   74,   80,   73,   81,   81,
       81,   81,  153,  212,   82,   99,   99,  154,  133,   83,

      133,  273,  100,   61,   67,   67,   61,   84,  242,   67,
       67,   85,  212,   86,   86,   86,   87,   74,  150,   74,
       99,   99,   99,   99,   88,   89,   90,  100,   91,  100,
       92,   99,   99,  133,   93,  133,   88,  197,  100,   89,
       90,  150,   99,   99,  134,   91,   99,   99,  132,  100,
      131,   99,   99,  100,  160,  160,   92,   85,  100,   94,
       94,   94,   94,   99,   99,   98,  130,  111,  102,  112,
      100,   89,   90,   97,   91,   99,   99,   99,   99,   96,
       95,   79,  100,  105,  100,   89,   90,   78,  113,   77,
      106,   91,  103,  107,  104,   76,  108,   75,  114,   99,

       99,  115,   99,   99,  109,  306,  100,   99,   99,  100,
       87,   87,   87,  110,  100,   99,   99,  116,  118,   99,
       99,   63,  100,   63,  117,  306,  100,   99,   99,  198,
      198,  198,  119,  306,  100,  159,  159,  159,  159,  306,
      164,  164,  164,  164,  161,  306,  161,  306,  123,  162,
      162,  162,  162,  306,  121,  120,  306,  122,  165,  165,
      165,  165,  306,  127,  306,  306,   99,   99,  306,  124,
      125,  128,  126,  100,   99,   99,  306,  129,  136,  306,
      137,  100,  155,  155,  155,  155,   99,   99,  306,  138,
      138,  138,  306,  100,   99,   99,   99,   99,  139,   99,

       99,  100,  152,  100,   99,   99,  100,  306,  140,  306,
      153,  100,  141,   99,   99,  154,  142,  166,   99,   99,
      100,  250,  250,  143,  306,  100,  144,  306,  145,  306,
      146,  306,  147,  155,  155,  155,  155,  168,  243,  243,
      243,  170,   99,   99,  167,  156,  157,  306,  157,  100,
      171,  306,  169,  306,  158,   99,   99,  306,  306,  156,
      157,  306,  100,   99,   99,  157,  306,  172,   99,   99,
      100,   99,   99,   99,   99,  100,   99,   99,  100,  306,
      100,   99,   99,  100,  173,   99,   99,  306,  100,   99,
       99,  306,  100,   99,   99,  306,  100,   99,   99,  306,

      100,  306,   99,   99,  100,   99,   99,   99,   99,  100,
      174,  306,  100,  306,  100,  306,  175,  306,  177,  306,
       99,   99,  306,  176,  306,  179,  178,  100,   99,   99,
       99,   99,  306,  306,  306,  100,  306,  100,  183,  180,
      182,   99,   99,  186,  187,  306,  181,  184,  100,  188,
       99,   99,  185,   99,   99,   99,   99,  100,  306,  306,
      100,  189,  100,  200,  306,  200,  160,  160,  201,  201,
      201,  201,  190,  306,  306,  192,  306,   99,   99,  191,
      162,  162,  162,  162,  100,  306,  193,  207,  306,  306,
       99,   99,  306,  165,  165,  165,  165,  100,  195,  306,

      196,  201,  201,  201,  201,  194,  202,  202,  202,  202,
      208,  208,  208,  208,   95,   99,   99,  306,  203,  204,
      306,  205,  100,  209,  306,  210,  306,  206,   99,   99,
      306,  211,  203,  204,  306,  100,  306,  209,  205,  306,
      306,  306,  210,  213,  220,  164,  164,  164,  164,   99,
       99,  306,   99,   99,   99,   99,  100,  214,   91,  100,
       91,  100,  215,   99,   99,  216,   93,   99,   99,  306,
      100,  214,   91,  306,  100,   99,   99,   91,   99,   99,
       99,   99,  100,  306,  306,  100,  306,  100,   99,   99,
      217,   99,   99,  306,  306,  100,   99,   99,  100,  306,

      221,   99,   99,  100,  218,  222,  306,  219,  100,  306,
       99,   99,   99,   99,   99,   99,  223,  100,  306,  100,
      306,  100,   99,   99,  306,  226,  224,   99,   99,  100,
       99,   99,  227,  225,  100,   99,   99,  100,   99,   99,
       99,   99,  100,   99,   99,  100,  306,  100,   99,   99,
      100,   99,   99,   99,   99,  100,  306,  228,  100,  306,
      100,   99,   99,  306,  229,   99,   99,  306,  100,  306,
      230,  306,  100,  247,  232,  247,  231,  233,  248,  248,
      248,  248,  250,  250,  236,  235,  249,  249,  249,  249,
      306,  306,  306,  234,  239,  245,  245,  245,  245,   99,

       99,  240,  237,  207,  238,  306,  100,  306,  157,  306,
      157,  306,  241,  306,   99,   99,  246,  208,  208,  208,
      208,  100,  157,  251,  251,  251,  251,  157,  306,  306,
      209,  306,  210,  253,  253,  253,  253,  306,  211,  306,
      254,  306,  254,  306,  209,  255,  255,  255,  255,  210,
       99,   99,   99,   99,   99,   99,  306,  100,  306,  100,
      256,  100,  306,   99,   99,   99,   99,   99,   99,  306,
      100,  306,  100,  306,  100,   99,   99,   99,   99,  306,
       99,   99,  100,  306,  100,   99,   99,  100,   99,   99,
       99,   99,  100,   99,   99,  100,  306,  100,   99,   99,

      100,  306,   99,   99,  306,  100,  306,  257,  258,  100,
       99,   99,   99,   99,  260,   99,   99,  100,  306,  100,
      259,  261,  100,   99,   99,  263,   99,   99,  306,  306,
      100,   99,   99,  100,  306,  265,  306,  306,  100,  262,
       99,   99,  306,  266,  306,  264,  306,  100,  306,   99,
       99,   99,   99,   99,   99,  267,  100,  306,  100,  306,
      100,  245,  245,  245,  245,  306,  306,  268,   99,   99,
      271,  306,  269,  306,  157,  100,  157,  306,  270,  306,
       99,   99,  246,  245,  245,  245,  245,  100,  157,  248,
      248,  248,  248,  157,  272,  274,  274,  274,  274,  255,

      255,  255,  255,  306,   99,   99,  306,  306,  204,  306,
      205,  100,   99,   99,   99,   99,  275,   99,   99,  100,
      306,  100,  204,  306,  100,  306,  306,  205,  249,  249,
      249,  249,  251,  251,  251,  251,  306,   99,   99,  306,
      276,  205,  306,  205,  100,  210,  306,  210,  306,  206,
      306,  278,  306,  211,  276,  205,   99,   99,  279,  210,
      205,  277,  306,  100,  210,  251,  251,  251,  251,   99,
       99,  306,   99,   99,   99,   99,  100,  306,  210,  100,
      210,  100,   99,   99,   99,   99,  211,   99,   99,  100,
      306,  100,  210,  306,  100,  280,  306,  210,   99,   99,

       99,   99,   99,   99,  306,  100,  306,  100,  306,  100,
      306,  306,  306,  283,  281,  306,  274,  274,  274,  274,
      306,  284,  289,  289,  289,  289,  282,  306,  306,  204,
      286,  205,  306,  285,  290,  306,  290,  275,  306,  291,
      291,  291,  291,  204,  287,   99,   99,  306,  205,   99,
       99,  306,  100,   99,   99,  306,  100,   99,   99,  306,
      100,  306,   99,   99,  100,   99,   99,   99,   99,  100,
       99,   99,  100,  306,  100,   99,   99,  100,   99,   99,
       99,   99,  100,  306,  306,  100,  306,  100,  291,  291,
      291,  291,  289,  289,  289,  289,  289,  289,  289,  289,

      292,  294,  295,  293,  306,  205,  296,  205,  306,  205,
      306,  205,  306,  275,  306,   99,   99,  275,  306,  205,
      306,  297,  100,  205,  205,   99,   99,  306,  205,   99,
       99,  306,  100,   99,   99,  306,  100,   99,   99,  306,
      100,   99,   99,  306,  100,  302,  302,  306,  100,  306,
       99,   99,   99,   99,   99,   99,  299,  100,  306,  100,
      306,  100,  302,  302,  304,  302,  302,  306,   99,   99,
      306,  306,  306,  306,  300,  100,  306,  306,  306,  306,
      306,  304,  301,  306,  304,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  305,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  304,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  304,  306,  306,  304,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
      101,  101,  306,  306,  101,  306,  101,  306,  101,  135,
      135,  306,  306,  135,  135,  135,  135,  135,  135,  148,

      148,  306,  148,  306,  148,  148,  148,  148,  148,  149,
      149,  149,  149,  149,  149,  306,  149,  149,  149,  149,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  163,  306,  163,  199,  306,  199,  244,  306,  244,
      252,  306,  252,  298,  306,  306,  306,  306,  306,  306,
      306,  298,  303,  303,  306,  306,  306,  306,  303,  303,
      303,   13,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static const flex_int16_t yy_chk[1427] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    4,    4,    4,
       11,    7,    8,  288,    7,    8,    9,   10,   11,   12,
      273,    9,   10,   15,   73,   15,   27,   12,   27,   27,
       27,   27,   73,  252,   28,   36,   36,   73,   59,   28,

       59,  242,   36,    3,    7,    8,    4,   28,  197,    9,
       10,   29,  163,   29,   29,   29,   29,   74,  149,   74,
       43,   43,   53,   53,   29,   29,   29,   43,   29,   53,
       29,   37,   37,  133,   29,  133,   29,  134,   37,   29,
       29,   71,   40,   40,   61,   29,   41,   41,   57,   40,
       55,   44,   44,   41,   88,   88,   29,   30,   44,   30,
       30,   30,   30,   42,   42,   35,   53,   43,   37,   43,
       42,   30,   30,   34,   30,   45,   45,   46,   46,   33,
       30,   26,   45,   41,   46,   30,   30,   24,   44,   23,
       41,   30,   40,   41,   40,   19,   41,   17,   44,   47,

       47,   44,   48,   48,   42,   13,   47,   49,   49,   48,
       87,   87,   87,   42,   49,   50,   50,   45,   46,   51,
       51,    6,   50,    5,   45,    0,   51,   52,   52,  138,
      138,  138,   46,   86,   52,   85,   85,   85,   85,   86,
       93,   93,   93,   93,   89,   86,   89,    0,   49,   89,
       89,   89,   89,    0,   48,   47,    0,   48,   95,   95,
       95,   95,    0,   51,    0,   86,   99,   99,    0,   50,
       50,   51,   50,   99,  101,  101,    0,   52,   67,    0,
       67,  101,  158,  158,  158,  158,  102,  102,    0,   67,
       67,   67,    0,  102,  103,  103,  104,  104,   67,  105,

      105,  103,  153,  104,  106,  106,  105,    0,   67,    0,
      153,  106,   67,  107,  107,  153,   67,  102,  108,  108,
      107,  207,  207,   67,    0,  108,   67,    0,   67,    0,
       67,    0,   67,   81,   81,   81,   81,  104,  198,  198,
      198,  106,  109,  109,  103,   81,   81,    0,   81,  109,
      107,    0,  105,    0,   81,  110,  110,    0,    0,   81,
       81,    0,  110,  111,  111,   81,    0,  108,  112,  112,
      111,  113,  113,  115,  115,  112,  114,  114,  113,    0,
      115,  116,  116,  114,  109,  117,  117,    0,  116,  118,
      118,    0,  117,  119,  119,    0,  118,  120,  120,    0,

      119,    0,  121,  121,  120,  122,  122,  123,  123,  121,
      110,    0,  122,    0,  123,    0,  111,    0,  113,    0,
      124,  124,    0,  112,    0,  115,  114,  124,  125,  125,
      126,  126,    0,    0,    0,  125,    0,  126,  120,  117,
      119,  127,  127,  122,  123,    0,  118,  121,  127,  123,
      128,  128,  121,  129,  129,  130,  130,  128,    0,    0,
      129,  123,  130,  156,    0,  156,  160,  160,  156,  156,
      156,  156,  124,    0,    0,  126,    0,  166,  166,  125,
      161,  161,  161,  161,  166,    0,  127,  160,    0,    0,
      172,  172,    0,  165,  165,  165,  165,  172,  129,    0,

      130,  200,  200,  200,  200,  128,  159,  159,  159,  159,
      162,  162,  162,  162,  165,  167,  167,    0,  159,  159,
        0,  159,  167,  162,    0,  162,    0,  159,  168,  168,
        0,  162,  159,  159,    0,  168,    0,  162,  159,    0,
        0,    0,  162,  164,  172,  164,  164,  164,  164,  169,
      169,    0,  170,  170,  171,  171,  169,  164,  164,  170,
      164,  171,  167,  173,  173,  168,  164,  174,  174,    0,
      173,  164,  164,    0,  174,  175,  175,  164,  176,  176,
      177,  177,  175,    0,    0,  176,    0,  177,  178,  178,
      169,  179,  179,    0,    0,  178,  180,  180,  179,    0,

      173,  181,  181,  180,  170,  174,    0,  171,  181,    0,
      182,  182,  183,  183,  184,  184,  175,  182,    0,  183,
        0,  184,  185,  185,    0,  178,  176,  186,  186,  185,
      187,  187,  179,  177,  186,  188,  188,  187,  189,  189,
      190,  190,  188,  191,  191,  189,    0,  190,  192,  192,
      191,  193,  193,  194,  194,  192,    0,  182,  193,    0,
      194,  195,  195,    0,  183,  196,  196,    0,  195,    0,
      184,    0,  196,  203,  186,  203,  185,  187,  203,  203,
      203,  203,  250,  250,  191,  190,  206,  206,  206,  206,
        0,    0,    0,  189,  194,  201,  201,  201,  201,  215,

      215,  195,  192,  250,  193,    0,  215,    0,  201,    0,
      201,    0,  196,    0,  216,  216,  201,  208,  208,  208,
      208,  216,  201,  211,  211,  211,  211,  201,    0,    0,
      208,    0,  208,  213,  213,  213,  213,    0,  208,    0,
      214,    0,  214,    0,  208,  214,  214,  214,  214,  208,
      217,  217,  218,  218,  219,  219,    0,  217,    0,  218,
      216,  219,    0,  220,  220,  221,  221,  222,  222,    0,
      220,    0,  221,    0,  222,  223,  223,  224,  224,    0,
      225,  225,  223,    0,  224,  226,  226,  225,  227,  227,
      228,  228,  226,  229,  229,  227,    0,  228,  230,  230,

      229,    0,  231,  231,    0,  230,    0,  219,  220,  231,
      232,  232,  233,  233,  222,  234,  234,  232,    0,  233,
      221,  225,  234,  235,  235,  227,  236,  236,    0,    0,
      235,  237,  237,  236,    0,  230,    0,    0,  237,  226,
      238,  238,    0,  231,    0,  229,    0,  238,    0,  239,
      239,  240,  240,  241,  241,  232,  239,    0,  240,    0,
      241,  245,  245,  245,  245,    0,    0,  234,  256,  256,
      237,    0,  235,    0,  245,  256,  245,    0,  236,    0,
      257,  257,  245,  246,  246,  246,  246,  257,  245,  247,
      247,  247,  247,  245,  241,  248,  248,  248,  248,  254,

      254,  254,  254,    0,  259,  259,    0,    0,  248,    0,
      248,  259,  258,  258,  261,  261,  248,  260,  260,  258,
        0,  261,  248,    0,  260,    0,    0,  248,  249,  249,
      249,  249,  251,  251,  251,  251,    0,  262,  262,    0,
      249,  249,    0,  249,  262,  251,    0,  251,    0,  249,
        0,  259,    0,  251,  249,  249,  263,  263,  260,  251,
      249,  258,    0,  263,  251,  255,  255,  255,  255,  264,
      264,    0,  265,  265,  266,  266,  264,    0,  255,  265,
      255,  266,  267,  267,  268,  268,  255,  269,  269,  267,
        0,  268,  255,    0,  269,  263,    0,  255,  270,  270,

      271,  271,  272,  272,    0,  270,    0,  271,    0,  272,
        0,    0,    0,  266,  264,    0,  274,  274,  274,  274,
        0,  267,  275,  275,  275,  275,  265,    0,    0,  274,
      269,  274,    0,  268,  276,    0,  276,  274,    0,  276,
      276,  276,  276,  274,  271,  277,  277,    0,  274,  278,
      278,    0,  277,  279,  279,    0,  278,  280,  280,    0,
      279,    0,  281,  281,  280,  282,  282,  283,  283,  281,
      284,  284,  282,    0,  283,  285,  285,  284,  286,  286,
      287,  287,  285,    0,    0,  286,    0,  287,  290,  290,
      290,  290,  289,  289,  289,  289,  291,  291,  291,  291,

      277,  280,  281,  278,    0,  289,  282,  289,    0,  291,
        0,  291,    0,  289,    0,  292,  292,  291,    0,  289,
        0,  283,  292,  291,  289,  293,  293,    0,  291,  294,
      294,    0,  293,  295,  295,    0,  294,  296,  296,    0,
      295,  297,  297,    0,  296,  298,  298,    0,  297,    0,
      299,  299,  300,  300,  301,  301,  292,  299,    0,  300,
        0,  301,  302,  302,  298,  303,  303,    0,  305,  305,
        0,    0,    0,    0,  295,  305,    0,    0,    0,    0,
        0,  302,  297,    0,  303,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  301,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  298,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  302,    0,    0,  303,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      312,  312,    0,    0,  312,    0,  312,    0,  312,  313,
      313,    0,    0,  313,  313,  313,  313,  313,  313,  314,

      314,    0,  314,    0,  314,  314,  314,  314,  314,  315,
      315,  315,  315,  315,  315,    0,  315,  315,  315,  315,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  317,    0,  317,  318,    0,  318,  319,    0,  319,
      320,    0,  320,  321,    0,    0,    0,    0,    0,    0,
        0,  321,  322,  322,    0,    0,    0,    0,  322,  322,
      322,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "d_lexer.l"
#line 5 "d_lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <math.h>
#include <float.h>
#include <errno.h>
#include <ctype.h>

void add_class_name(const char* name);
int is_class_name(const char* name);
void reset_class_table();
void print_class_table();
void handle_hex_escape(char* buffer, char* yytext);
void handle_octal_escape(char* buffer, char* yytext);
void finish_char(char* buffer, int line);
void strip_underscores(char* buf, const char* src);
long parse_binary(const char* yytext);
long parse_octal(const char* yytext);
long parse_hexadecimal(const char* yytext);
long parse_decimal(const char* yytext);
int get_int(const char* yytext);
float get_float(const char* yytext);
void process_possible_function(int yyleng, const char* yytext);
int is_keyword(const char* word);
#line 890 "lex.yy.c"

#line 892 "lex.yy.c"

#define INITIAL 0
#define FIRST_PASS 1
#define COMMENT 2
#define STRING 3
#define CHAR 4
#define MULTILINE_COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "d_lexer.l"



#line 42 "d_lexer.l"
    int line = 1;
    char tmp[8192];
    int string_pos = 0;
    int comment_pos = 0;
    int value_int;
    float value_float;


#line 1127 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 306 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 50 "d_lexer.l"
{
    char class_name[256];
    sscanf(yytext, "class %s", class_name);
    char* end = strchr(class_name, '{');
    if (!end) end = strchr(class_name, ':');
    if (end) *end = '\0';
    add_class_name(class_name);
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 59 "d_lexer.l"
{ line++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "d_lexer.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "d_lexer.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "d_lexer.l"
;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 64 "d_lexer.l"
{ line++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 77 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "d_lexer.l"
{ printf("Null: null\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "d_lexer.l"
{ printf("NaN: NaN\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "d_lexer.l"
{ printf("Bool: true\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "d_lexer.l"
{ printf("Bool: false\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "d_lexer.l"
{ strcpy(tmp,""); BEGIN(CHAR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "d_lexer.l"
{ strcpy(tmp,""); string_pos = line; BEGIN(STRING); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "d_lexer.l"
{ strcat(tmp,yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "d_lexer.l"
{ strcat(tmp,yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "d_lexer.l"
{ strcat(tmp,"\b"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "d_lexer.l"
{ strcat(tmp,"\f"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "d_lexer.l"
{ strcat(tmp,"\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "d_lexer.l"
{ strcat(tmp,"\r"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "d_lexer.l"
{ strcat(tmp,"\t"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "d_lexer.l"
{ strcat(tmp,"\v"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "d_lexer.l"
{ strcat(tmp,"\'"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "d_lexer.l"
{ strcat(tmp,"\""); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "d_lexer.l"
{ strcat(tmp,"\\"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "d_lexer.l"
{ strcat(tmp,"\?"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "d_lexer.l"
{ handle_hex_escape( tmp, yytext ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "d_lexer.l"
{ handle_octal_escape( tmp, yytext ); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 119 "d_lexer.l"
{ line++; strcat(tmp,"\n"); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 120 "d_lexer.l"
{ printf("ERROR! line break found in char literal in row: %d\n", line); line++; }
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
#line 121 "d_lexer.l"
{ printf("ERROR! Haven't found closing quotes in string with position: %d\n", string_pos); BEGIN(INITIAL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 122 "d_lexer.l"
{ printf("Found String literal: %s\n",tmp); BEGIN(INITIAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "d_lexer.l"
{ finish_char(tmp, line); BEGIN(INITIAL); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 126 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 127 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 128 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 134 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 135 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 136 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 137 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 138 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 141 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 142 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 143 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 144 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 145 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 148 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 149 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 150 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 151 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 152 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 153 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 154 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 155 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 156 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 158 "d_lexer.l"
{ printf("Int: %s\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 159 "d_lexer.l"
{ printf("Int: %s (binary with separators)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 160 "d_lexer.l"
{ printf("Int: %s (octal)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 161 "d_lexer.l"
{ printf("ERROR! Incorrect octal number: %s in row: %d\n", yytext, line); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 162 "d_lexer.l"
{ printf("Int: %s (hex with separators)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 164 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 165 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 166 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 167 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 168 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 171 "d_lexer.l"
{ tmp[0] = '\0'; BEGIN(COMMENT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 172 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 173 "d_lexer.l"
{ printf("Found comment: %s\n", tmp); line++; BEGIN(INITIAL); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 175 "d_lexer.l"
{ tmp[0] = '\0'; comment_pos = line; BEGIN(MULTILINE_COMMENT); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 177 "d_lexer.l"
{ line++; strcat(tmp, yytext); }
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 178 "d_lexer.l"
{ line++; strcat(tmp, yytext); }
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 179 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 180 "d_lexer.l"
{ printf("Found multiline comment: %s\n", tmp); BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 182 "d_lexer.l"
{ printf("ERROR! Multiline comment with position %d: \n\"%s\" \nisn't closed!\n", line, tmp); BEGIN(INITIAL); }
	YY_BREAK
case 111:
/* rule 111 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 184 "d_lexer.l"
{ process_possible_function(yyleng, yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 186 "d_lexer.l"
{
    if (is_class_name(yytext)) {
        printf("Classname: %s\n", yytext);
    } else {
        printf("Found identifier: %s\n", yytext);
    }
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 194 "d_lexer.l"
{ printf("LEXICAL ERROR: Unknown character '%s' at line %d\n", yytext, line); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 196 "d_lexer.l"
ECHO;
	YY_BREAK
#line 1786 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FIRST_PASS):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 306);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "d_lexer.l"


#define MAX_CLASSES 1000
#define MAX_CLASS_NAME 256

typedef struct {
    char names[MAX_CLASSES][MAX_CLASS_NAME];
    int count;
} ClassTable;

ClassTable classTable = { .count = 0 };

void add_class_name(const char* name) {
    if (classTable.count < MAX_CLASSES) {
        strncpy(classTable.names[classTable.count], name, MAX_CLASS_NAME - 1);
        classTable.names[classTable.count][MAX_CLASS_NAME - 1] = '\0';
        classTable.count++;
    }
}

int is_class_name(const char* name) {
    for (int i = 0; i < classTable.count; i++) {
        if (strcmp(classTable.names[i], name) == 0) {
            return 1;
        }
    }
    return 0;
}

void reset_class_table() {
    classTable.count = 0;
}

void print_class_table() {
    printf("\n=== FOUND CLASSES (%d total) ===\n", classTable.count);
    for (int i = 0; i < classTable.count; i++) {
        printf("  %d. %s\n", i + 1, classTable.names[i]);
    }
    printf("================================\n\n");
}

int is_keyword(const char* word) {
    const char* keywords[] = {
        "if", "else", "while", "for", "do", "switch", "case", 
        "return", "break", "continue", "int", "char", "float",
        "string", "foreach", "super", "override", "enum", "real", 
        "double", "void", "class", "new", "this", "ref", NULL
    };
    
    for (int i = 0; keywords[i] != NULL; i++) {
        if (strcmp(word, keywords[i]) == 0) {
            return 1;
        }
    }
    return 0;
}

void process_possible_function(int yyleng, const char* yytext) {
    char func_name[256];
    int i = 0;
    while (i < yyleng && (isalnum(yytext[i]) || yytext[i] == '_')) {
        func_name[i] = yytext[i];
        i++;
    }
    func_name[i] = '\0';

    if (is_keyword(func_name)) {
        printf("Keyword: %s\n", func_name);
    } else {
        printf("Function: %s\n", func_name);
    }
}

void handle_hex_escape(char* buffer, char* yytext) {
    char dig[2];
    char *a;
    dig[0] = (char)strtol(yytext+2, &a, 16);
    dig[1] = '\0';
    strcat(buffer, dig);
}

void handle_octal_escape(char* buffer, char* yytext) {
    char dig[2];
    char *a;
    dig[0] = (char)strtol(yytext+1, &a, 8);
    dig[1] = '\0';
    strcat(buffer, dig);
}

void finish_char(char* buffer, int line) {
    if(strlen(buffer) != 1) {
        printf("ERROR! char length != 1 in row: %d\n", line);
    } else {
        printf("Found Char literal: %s\n", buffer);
    }
}

void strip_underscores(char* buf, const char* src) {
    char* d = buf;
    for (const char* s = src; *s; s++) {
        if (*s != '_')
            *d++ = *s;
    }
    *d = '\0';
}

long parse_binary(const char* yytext) {
    for (int i = 2; yytext[i] != '\0'; i++) {
        if (yytext[i] != '0' && yytext[i] != '1') {
            fprintf(stderr, "Error: Invalid binary digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext + 2, NULL, 2);
}

long parse_octal(const char* yytext) {
    for (int i = 1; yytext[i] != '\0'; i++) {
        if (yytext[i] < '0' || yytext[i] > '7') {
            fprintf(stderr, "Error: Invalid octal digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext, NULL, 8);
}

long parse_hexadecimal(const char* yytext) {
    for (int i = 2; yytext[i] != '\0'; i++) {
        if (!isxdigit(yytext[i])) {
            fprintf(stderr, "Error: Invalid hex digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext + 2, NULL, 16);
}

long parse_decimal(const char* yytext) {
    for (int i = 0; yytext[i] != '\0'; i++) {
        if (!isdigit(yytext[i])) {
            fprintf(stderr, "Error: Invalid digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext, NULL, 10);
}

int get_int(const char* yytext) {
    char clean[64];
    strip_underscores(clean, yytext);
    long val;

    if (strncmp(clean, "0b", 2) == 0 || strncmp(clean, "0B", 2) == 0) {
        val = parse_binary(clean);
    }
    else if (strncmp(clean, "0x", 2) == 0 || strncmp(clean, "0X", 2) == 0) {
        val = parse_hexadecimal(clean);
    }
    else if (clean[0] == '0') {
        val = parse_octal(clean);
    }
    else val = parse_decimal(clean);

    if (val > INT_MAX) {
        printf("Warning: Number exceeds int range, truncated to INT_MAX.\n");
        return INT_MAX;
    }

    return (int)val;
}

float get_float(const char* yytext) {
    char clean[64];
    strip_underscores(clean, yytext);
    errno = 0;
    char* endptr;
    float val = strtof(clean, &endptr);

    if ((errno == ERANGE && val == HUGE_VALF) || val > FLT_MAX) {
        printf("Warning: Float value exceeds range, truncated to FLT_MAX.\n");
        return FLT_MAX;
    }

    return val;
}

int main(int argc, char* argv[]) {
    FILE *input_file = NULL;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input_file.d>\n", argv[0]);
        return 1;
    }

    input_file = fopen(argv[1], "r");
    if (!input_file) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", argv[1]);
        return 1;
    }

    yyin = input_file;
    BEGIN(FIRST_PASS);
    
    while (yylex() != 0) {}

    fclose(input_file);
    print_class_table();
    
    input_file = fopen(argv[1], "r");
    if (!input_file) {
        fprintf(stderr, "Error: Cannot open file '%s' for second pass\n", argv[1]);
        return 1;
    }

    yyin = input_file;
    BEGIN(INITIAL);
    yyrestart(yyin);
    
    while (yylex() != 0) {}

    fclose(input_file);
    
    return 0;
}

