
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[346] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      135,  133,   24,   25,   99,   62,  133,   61,  104,  105,
       89,   87,  111,   88,  102,   90,  113,  113,  112,  110,
       83,   91,   85,  132,  132,  108,  109,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  106,  133,  107,  103,   23,   22,   21,   11,
       16,   23,   23,    3,    4,   12,   14,   15,  134,   17,
       19,   20,  134,    6,    7,  134,  124,  125,   63,   77,
       79,  134,   64,   78,   80,  127,  128,  134,   24,   82,

       97,   94,   92,   93,  101,  120,  126,  123,   95,    0,
      115,  116,    0,    0,  118,  122,    0,    0,  113,    0,
       84,   81,   86,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,   35,  132,  132,  132,  132,  132,   30,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,   98,   96,   22,    5,    2,    0,
       12,   13,   17,   18,    6,    7,    9,    8,    0,   10,
       63,   72,   71,   76,   74,   73,   65,   66,   67,   68,
       69,   70,    0,   64,  127,  128,  130,  129,    0,  131,
      100,  120,    0,  120,    0,  118,  114,    0,  118,  117,

        0,  113,   58,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,   37,   26,   41,  132,
      132,  132,  132,  132,  132,   55,  132,  132,  132,  132,
      132,  132,  132,  132,    0,   76,   75,    0,  120,  118,
        0,  118,  119,    0,    0,  118,  118,  121,    0,    0,
        0,    0,   53,   29,  132,   33,   27,  132,  132,  132,
      132,   31,   56,  132,  132,  132,   57,  132,  132,  132,
      132,   49,  132,  132,  132,  132,   54,   59,   40,  132,
        0,   76,   75,  120,    0,    0,  118,  119,  114,  121,
      117,  119,    0,  121,   43,   44,  132,  132,  132,   60,

       47,  132,  132,  132,  132,  132,  132,  132,   45,  132,
       36,    0,  118,    0,    0,  132,  132,   48,  132,  132,
      132,  132,   51,   39,   28,   32,    0,  119,    0,  119,
      132,   34,   38,  132,   50,  132,    0,   42,   46,  132,
        0,    0,    1,   52,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   33,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   34,   31,   31,
       35,   36,   37,    1,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       31,   31,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    5,    1,    1,
        6,    1,    1,    1,    1,    1,    7,    7,    7,    7,
        8,    1,    1,    1,    1,    1,    9,    9,    9,    9,
       10,   10,   10,   10,    1,   11,    1,   10,    9,    9,
        9,    9,    9,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[372] =
    {   0,
        0,    0,   63,   70,  809,  808,   74,   78,   67,   79,
       80,   82,  807,  806,   86,   91,   87,   93,   95,   96,
      808,  813,   98,  813,  779,  813,  795,  813,  813,  813,
      777,  772,  813,  771,  101,  101,  115,  161,  813,  813,
      770,  769,  768,    0,  752,  813,  813,  731,   72,  102,
       85,   87,  111,   95,   99,  727,   51,  739,  109,  115,
      727,  715,  813,  688,  813,  724,  813,  168,  813,  813,
      813,  141,  690,  813,  813,    0,  813,  813,    0,    0,
      813,  813,    0,  735,  813,  171,  813,  813,    0,  813,
      813,  205,    0,  813,  813,  716,  813,  181,  169,  813,

      813,  813,  813,  813,  690,  249,  813,  813,  813,  183,
      149,  177,  168,  200,  813,  813,    0,  208,    0,  215,
      813,  813,  813,    0,  664,  639,  632,  632,  619,  630,
      528,  515,  521,  505,  506,  503,  509,  504,  501,    0,
      498,  493,  501,  505,  115,  504,  198,  489,  489,  494,
      480,  467,  473,  472,  813,  813,  204,  813,  813,  479,
        0,  813,    0,  813,  513,  813,  813,  813,  227,  813,
        0,  813,  813,  229,  813,  813,  813,  813,  813,  813,
      813,  813,    0,    0,  511,  813,  813,  813,  241,  813,
      813,    0,  271,  813,  253,  282,  198,  257,  286,  475,

      321,  277,    0,  460,  461,  469,  461,  448,  446,  443,
      459,  446,  440,  427,  421,  436,  430,    0,    0,  422,
      415,  409,  395,  401,  400,    0,  389,  393,  391,  376,
      376,  386,  384,  375,  363,  290,    0,  325,  337,    0,
      354,  813,  813,  329,  222,  359,  813,  813,  343,    0,
      365,  376,    0,    0,  364,    0,    0,  355,  362,  345,
      338,    0,    0,  337,  302,  298,    0,  278,  290,  285,
      280,    0,  269,  271,  267,  278,    0,    0,    0,  274,
      258,  813,  813,  381,  387,  397,  403,  436,  410,  440,
      272,    0,  419,  473,    0,    0,  235,  235,  239,    0,

        0,  239,  217,  206,  219,  217,  204,  208,    0,  205,
        0,  248,  477,  425,  511,  172,  165,    0,  161,  156,
      145,   84,    0,    0,    0,    0,  129,  515,  444,  519,
       70,    0,    0,   66,    0,   45,  331,    0,    0,   26,
      479,  485,  813,    0,  813,  568,  579,  590,  601,  612,
      623,  634,  645,  656,  661,  671,  681,  692,  702,  713,
      724,  735,  745,  755,  766,  771,  774,  777,  780,  788,
      797
    } ;

static const flex_int16_t yy_def[372] =
    {   0,
      345,    1,  346,  346,  347,  347,  348,  348,  349,  349,
      350,  350,  351,  351,  352,  352,  353,  353,  354,  354,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  355,  355,  345,  345,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  356,  345,  345,  357,  358,
      345,  345,  359,  360,  345,  361,  345,  345,  362,  345,
      345,  345,  363,  345,  345,  364,  345,  365,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
       37,  111,  345,  345,  345,  345,  366,  345,   38,  345,
      345,  345,  345,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  345,  345,  345,  345,  345,  345,
      356,  345,  358,  345,  360,  345,  345,  345,  361,  345,
      362,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  367,  363,  364,  345,  345,  345,  365,  345,
      345,  106,  345,  345,  345,  345,  345,  345,  345,  366,

      345,  201,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  345,  345,  368,  345,  345,  196,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  369,
      345,  345,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      369,  288,  345,  345,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  345,  345,  345,  345,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  370,  345,  345,  345,
      355,  355,  355,  355,  355,  355,  371,  355,  355,  355,
      345,  371,  345,  355,    0,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345
    } ;

static const flex_int16_t yy_nxt[878] =
    {   0,
       22,   23,   24,   23,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   38,   38,
       39,   40,   41,   42,   43,   22,   44,   44,   44,   44,
       44,   44,   45,   44,   46,   22,   47,   44,   48,   49,
       50,   51,   52,   53,   44,   44,   54,   44,   44,   44,
       55,   56,   57,   58,   59,   60,   44,   61,   62,   44,
       63,   64,   65,   66,   68,   69,   68,  344,   70,   81,
       71,   68,   69,   68,   82,   70,   77,   71,   72,   78,
       77,   81,   85,   78,   85,   72,   82,  340,   90,   94,
       86,   91,   86,   90,   95,   94,   91,   97,   97,   99,

       95,   99,   83,   73,  145,   98,   98,  146,  339,   79,
       73,  107,  338,   79,   83,  105,  108,  106,  106,  106,
      106,   92,   92,  127,  109,  128,   92,  133,   92,  110,
      327,  111,  111,  111,  112,  135,  134,  136,  140,  336,
      129,  142,  113,  114,  115,  141,  116,  130,  117,  137,
      131,  158,  118,  132,  113,  143,  159,  114,  115,  138,
      151,  222,  139,  116,  148,  149,  223,  150,  152,  157,
       99,  157,   99,  168,  117,  110,  345,  119,  119,  119,
      119,  169,  345,  188,  197,  197,  170,  335,  345,  114,
      115,  189,  116,  112,  112,  112,  190,  334,  120,  196,

      196,  196,  196,  114,  115,  157,  333,  157,  345,  116,
      172,  198,  173,  198,  197,  197,  199,  199,  199,  199,
      332,  174,  174,  174,  201,  201,  201,  201,  331,  168,
      175,  202,  202,  202,  202,  245,  225,  169,  289,  289,
      176,  226,  170,  188,  177,  236,  236,  236,  178,  327,
      326,  189,  325,  227,  324,  179,  190,  323,  180,  322,
      181,  321,  182,  320,  183,  192,  192,  192,  192,  192,
      192,  192,  192,  199,  199,  199,  199,  193,  194,  319,
      194,  318,  238,  317,  238,  316,  195,  239,  239,  239,
      239,  193,  194,  202,  202,  202,  202,  194,  240,  240,

      240,  240,  246,  246,  246,  246,  282,  282,  282,  250,
      241,  242,  312,  243,  120,  247,  311,  248,  310,  244,
      309,  308,  307,  249,  241,  242,  306,  305,  304,  247,
      243,  303,  341,  341,  248,  251,  302,  201,  201,  201,
      201,  239,  239,  239,  239,  288,  288,  288,  288,  252,
      116,  343,  116,  284,  284,  284,  284,  301,  118,  290,
      290,  290,  290,  252,  116,  286,  194,  286,  194,  116,
      287,  287,  287,  287,  285,  246,  246,  246,  246,  300,
      194,  292,  292,  292,  292,  194,  299,  293,  247,  293,
      248,  343,  294,  294,  294,  294,  249,  284,  284,  284,

      284,  298,  247,  284,  284,  284,  284,  248,  297,  296,
      194,  295,  194,  287,  287,  287,  287,  281,  285,  313,
      313,  313,  313,  280,  194,  279,  289,  289,  278,  194,
      277,  276,  242,  275,  243,  294,  294,  294,  294,  274,
      314,  328,  328,  328,  328,  273,  242,  245,  272,  271,
      270,  243,  288,  288,  288,  288,  290,  290,  290,  290,
      330,  330,  330,  330,  315,  243,  269,  243,  268,  248,
      267,  248,  266,  244,  265,  264,  263,  249,  315,  243,
      341,  341,  262,  248,  243,  261,  341,  341,  248,  290,
      290,  290,  290,  313,  313,  313,  313,  260,  259,  343,

      258,  257,  248,  256,  248,  343,  242,  255,  243,  254,
      249,  253,  250,  186,  314,  166,  248,  235,  234,  233,
      242,  248,  329,  232,  329,  243,  231,  330,  330,  330,
      330,  328,  328,  328,  328,  328,  328,  328,  328,  343,
      230,  229,  228,  224,  243,  343,  243,  221,  243,  220,
      243,  219,  314,  218,  217,  216,  314,  215,  243,  214,
      213,  212,  243,  243,  211,  210,  209,  243,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,  124,  208,  124,
      124,  161,  161,  207,  206,  161,  161,  161,  161,  161,
      161,  162,  162,  205,  162,  162,  162,  162,  162,  162,
      162,  162,  163,  163,  204,  163,  203,  163,  163,  163,

      163,  163,  164,  164,  191,  164,  164,  164,  164,  164,
      164,  164,  164,  165,  165,  165,  165,  165,  186,  165,
      165,  165,  165,  165,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  171,  171,  166,  160,  171,
      171,  171,  171,  171,  171,  184,  184,  156,  184,  155,
      184,  184,  184,  184,  184,  185,  185,  185,  185,  185,
      154,  185,  185,  185,  185,  185,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  200,  153,  200,
      237,  147,  237,  283,  144,  283,  291,  126,  291,  337,
      125,  123,  122,  121,  104,  103,  337,  337,  342,  342,

      102,  101,  100,  342,  342,  342,  342,  345,   88,   88,
       75,   75,   21,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345
    } ;

static const flex_int16_t yy_chk[878] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,  340,    3,    9,
        3,    4,    4,    4,    9,    4,    7,    4,    3,    7,
        8,   10,   11,    8,   12,    4,   10,  336,   15,   17,
       11,   15,   12,   16,   17,   18,   16,   19,   20,   23,

       18,   23,    9,    3,   57,   19,   20,   57,  334,    7,
        4,   36,  331,    8,   10,   35,   36,   35,   35,   35,
       35,   15,   17,   49,   36,   49,   16,   51,   18,   37,
      327,   37,   37,   37,   37,   52,   51,   52,   54,  322,
       50,   55,   37,   37,   37,   54,   37,   50,   37,   53,
       50,   72,   37,   50,   37,   55,   72,   37,   37,   53,
       60,  145,   53,   37,   59,   59,  145,   59,   60,   68,
       99,   68,   99,   86,   37,   38,  111,   38,   38,   38,
       38,   86,  111,   98,  113,  113,   86,  321,  111,   38,
       38,   98,   38,  112,  112,  112,   98,  320,   38,  110,

      110,  110,  110,   38,   38,  157,  319,  157,  111,   38,
       92,  114,   92,  114,  197,  197,  114,  114,  114,  114,
      317,   92,   92,   92,  118,  118,  118,  118,  316,  169,
       92,  120,  120,  120,  120,  197,  147,  169,  245,  245,
       92,  147,  169,  189,   92,  174,  174,  174,   92,  312,
      310,  189,  308,  147,  307,   92,  189,  306,   92,  305,
       92,  304,   92,  303,   92,  106,  106,  106,  106,  195,
      195,  195,  195,  198,  198,  198,  198,  106,  106,  302,
      106,  299,  193,  298,  193,  297,  106,  193,  193,  193,
      193,  106,  106,  202,  202,  202,  202,  106,  196,  196,

      196,  196,  199,  199,  199,  199,  236,  236,  236,  291,
      196,  196,  281,  196,  202,  199,  280,  199,  276,  196,
      275,  274,  273,  199,  196,  196,  271,  270,  269,  199,
      196,  268,  337,  337,  199,  201,  266,  201,  201,  201,
      201,  238,  238,  238,  238,  244,  244,  244,  244,  201,
      201,  337,  201,  239,  239,  239,  239,  265,  201,  249,
      249,  249,  249,  201,  201,  241,  239,  241,  239,  201,
      241,  241,  241,  241,  239,  246,  246,  246,  246,  264,
      239,  251,  251,  251,  251,  239,  261,  252,  246,  252,
      246,  337,  252,  252,  252,  252,  246,  284,  284,  284,

      284,  260,  246,  285,  285,  285,  285,  246,  259,  258,
      284,  255,  284,  286,  286,  286,  286,  235,  284,  287,
      287,  287,  287,  234,  284,  233,  289,  289,  232,  284,
      231,  230,  287,  229,  287,  293,  293,  293,  293,  228,
      287,  314,  314,  314,  314,  227,  287,  289,  225,  224,
      223,  287,  288,  288,  288,  288,  290,  290,  290,  290,
      329,  329,  329,  329,  288,  288,  222,  288,  221,  290,
      220,  290,  217,  288,  216,  215,  214,  290,  288,  288,
      341,  341,  213,  290,  288,  212,  342,  342,  290,  294,
      294,  294,  294,  313,  313,  313,  313,  211,  210,  341,

      209,  208,  294,  207,  294,  342,  313,  206,  313,  205,
      294,  204,  200,  185,  313,  165,  294,  160,  154,  153,
      313,  294,  315,  152,  315,  313,  151,  315,  315,  315,
      315,  328,  328,  328,  328,  330,  330,  330,  330,  341,
      150,  149,  148,  146,  328,  342,  328,  144,  330,  143,
      330,  142,  328,  141,  139,  138,  330,  137,  328,  136,
      135,  134,  330,  328,  133,  132,  131,  330,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  355,  130,  355,
      355,  356,  356,  129,  128,  356,  356,  356,  356,  356,
      356,  357,  357,  127,  357,  357,  357,  357,  357,  357,
      357,  357,  358,  358,  126,  358,  125,  358,  358,  358,

      358,  358,  359,  359,  105,  359,  359,  359,  359,  359,
      359,  359,  359,  360,  360,  360,  360,  360,   96,  360,
      360,  360,  360,  360,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  362,  362,   84,   73,  362,
      362,  362,  362,  362,  362,  363,  363,   66,  363,   64,
      363,  363,  363,  363,  363,  364,  364,  364,  364,  364,
       62,  364,  364,  364,  364,  364,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  366,   61,  366,
      367,   58,  367,  368,   56,  368,  369,   48,  369,  370,
       45,   43,   42,   41,   34,   32,  370,  370,  371,  371,

       31,   27,   25,  371,  371,  371,  371,   21,   14,   13,
        6,    5,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "d_lexer.l"
#line 5 "d_lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <math.h>
#include <float.h>
#include <errno.h>
#include <ctype.h>

void add_class_name(const char* name);
int is_class_name(const char* name);
void reset_class_table();
void print_class_table();
void handle_hex_escape(char* buffer, char* yytext);
void handle_octal_escape(char* buffer, char* yytext);
void finish_char(char* buffer, int line);
void strip_underscores(char* buf, const char* src);
long parse_binary(const char* yytext);
long parse_octal(const char* yytext);
long parse_hexadecimal(const char* yytext);
long parse_decimal(const char* yytext);
int get_int(const char* yytext);
float get_float(const char* yytext);
#line 780 "lex.yy.c"

#line 782 "lex.yy.c"

#define INITIAL 0
#define FIRST_PASS 1
#define FP_COMMENT 2
#define FP_STRING 3
#define FP_CHAR 4
#define FP_MULTILINE_COMMENT 5
#define COMMENT 6
#define STRING 7
#define CHAR 8
#define MULTILINE_COMMENT 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "d_lexer.l"



#line 41 "d_lexer.l"
    int line = 1;
    char tmp[8192];
    int string_pos = 0;
    int comment_pos = 0;
    int value_int;
    float value_float;


#line 1021 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 346 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 345 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 49 "d_lexer.l"
{
    char class_name[256];
    sscanf(yytext, "class %s", class_name);
    char* end = strchr(class_name, '{');
    if (!end) end = strchr(class_name, ':');
    if (end) *end = '\0';
    add_class_name(class_name);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "d_lexer.l"
{ BEGIN(FP_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "d_lexer.l"
;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 60 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "d_lexer.l"
{ BEGIN(FP_MULTILINE_COMMENT); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 "d_lexer.l"
;
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 64 "d_lexer.l"
;
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 65 "d_lexer.l"
;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 66 "d_lexer.l"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case YY_STATE_EOF(FP_MULTILINE_COMMENT):
#line 68 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 70 "d_lexer.l"
{ BEGIN(FP_STRING); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "d_lexer.l"
;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "d_lexer.l"
;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 73 "d_lexer.l"
;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case YY_STATE_EOF(FP_STRING):
#line 75 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "d_lexer.l"
{ BEGIN(FP_CHAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "d_lexer.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "d_lexer.l"
;
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 80 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 81 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case YY_STATE_EOF(FP_CHAR):
#line 82 "d_lexer.l"
{ BEGIN(FIRST_PASS); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 84 "d_lexer.l"
;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "d_lexer.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "d_lexer.l"
;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "d_lexer.l"
;
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 89 "d_lexer.l"
{ line++; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 93 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 94 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 97 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "d_lexer.l"
{ printf("Keyword: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "d_lexer.l"
{ printf("Null: null\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "d_lexer.l"
{ printf("NaN: NaN\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "d_lexer.l"
{ printf("Bool: true\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "d_lexer.l"
{ printf("Bool: false\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 "d_lexer.l"
{ strcpy(tmp,""); BEGIN(CHAR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "d_lexer.l"
{ strcpy(tmp,""); string_pos = line; BEGIN(STRING); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 "d_lexer.l"
{ strcat(tmp,yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 "d_lexer.l"
{ strcat(tmp,yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "d_lexer.l"
{ strcat(tmp,"\b"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "d_lexer.l"
{ strcat(tmp,"\f"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "d_lexer.l"
{ strcat(tmp,"\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "d_lexer.l"
{ strcat(tmp,"\r"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "d_lexer.l"
{ strcat(tmp,"\t"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "d_lexer.l"
{ strcat(tmp,"\v"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 139 "d_lexer.l"
{ strcat(tmp,"\'"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "d_lexer.l"
{ strcat(tmp,"\""); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "d_lexer.l"
{ strcat(tmp,"\\"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 142 "d_lexer.l"
{ strcat(tmp,"\?"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "d_lexer.l"
{ handle_hex_escape( tmp, yytext ); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 144 "d_lexer.l"
{ handle_octal_escape( tmp, yytext ); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 145 "d_lexer.l"
{ line++; strcat(tmp,"\n"); }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 146 "d_lexer.l"
{ printf("ERROR! line break found in char literal in row: %d\n", line); line++; }
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
#line 147 "d_lexer.l"
{ printf("ERROR! Haven't found closing quotes in string with position: %d\n", string_pos); BEGIN(INITIAL); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "d_lexer.l"
{ printf("Found String literal: %s\n",tmp); BEGIN(INITIAL); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 149 "d_lexer.l"
{ finish_char(tmp, line); BEGIN(INITIAL); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 166 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 168 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 169 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 173 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 175 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 176 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 177 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 178 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 179 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 180 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 181 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 182 "d_lexer.l"
{ printf("Separator: %s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 183 "d_lexer.l"
{ printf("Operator: %s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 185 "d_lexer.l"
{ printf("Int: %s\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 186 "d_lexer.l"
{ printf("Int: %s (binary with separators)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 187 "d_lexer.l"
{ printf("Int: %s (octal)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 188 "d_lexer.l"
{ printf("ERROR! Incorrect octal number: %s in row: %d\n", yytext, line); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 189 "d_lexer.l"
{ printf("Int: %s (hex with separators)\n", yytext); value_int = get_int(yytext); printf("Parsed Int: %d\n", value_int); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 191 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 192 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 193 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 194 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 195 "d_lexer.l"
{ printf("Float: %s\n", yytext); value_float = get_float(yytext); printf("Parsed Float: %f\n", value_float); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 198 "d_lexer.l"
{ tmp[0] = '\0'; BEGIN(COMMENT); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 199 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 200 "d_lexer.l"
{ printf("Found comment: %s\n", tmp); line++; BEGIN(INITIAL); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 202 "d_lexer.l"
{ tmp[0] = '\0'; comment_pos = line; BEGIN(MULTILINE_COMMENT); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 203 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 204 "d_lexer.l"
{ line++; strcat(tmp, yytext); }
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 205 "d_lexer.l"
{ line++; strcat(tmp, yytext); }
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 206 "d_lexer.l"
{ strcat(tmp, yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 207 "d_lexer.l"
{ printf("Found multiline comment: %s\n", tmp); BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 209 "d_lexer.l"
{ printf("ERROR! Multiline comment with position %d: \n\"%s\" \nisn't closed!\n", line, tmp); BEGIN(INITIAL); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 211 "d_lexer.l"
{
    if (is_class_name(yytext)) {
        printf("CLASSNAME: %s\n", yytext);
    } else {
        printf("Found identifier: %s\n", yytext);
    }
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 219 "d_lexer.l"
{ printf("LEXICAL ERROR: Unknown character '%s' at line %d\n", yytext, line); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 221 "d_lexer.l"
ECHO;
	YY_BREAK
#line 1793 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FIRST_PASS):
case YY_STATE_EOF(FP_COMMENT):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 346 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 346 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 345);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "d_lexer.l"


#define MAX_CLASSES 1000
#define MAX_CLASS_NAME 256

typedef struct {
    char names[MAX_CLASSES][MAX_CLASS_NAME];
    int count;
} ClassTable;

ClassTable classTable = { .count = 0 };

void add_class_name(const char* name) {
    if (classTable.count < MAX_CLASSES) {
        strncpy(classTable.names[classTable.count], name, MAX_CLASS_NAME - 1);
        classTable.names[classTable.count][MAX_CLASS_NAME - 1] = '\0';
        classTable.count++;
    }
}

int is_class_name(const char* name) {
    for (int i = 0; i < classTable.count; i++) {
        if (strcmp(classTable.names[i], name) == 0) {
            return 1;
        }
    }
    return 0;
}

void reset_class_table() {
    classTable.count = 0;
}

void print_class_table() {
    printf("\n=== FOUND CLASSES (%d total) ===\n", classTable.count);
    for (int i = 0; i < classTable.count; i++) {
        printf("  %d. %s\n", i + 1, classTable.names[i]);
    }
    printf("================================\n\n");
}

void handle_hex_escape(char* buffer, char* yytext) {
    char dig[2];
    char *a;
    dig[0] = (char)strtol(yytext+2, &a, 16);
    dig[1] = '\0';
    strcat(buffer, dig);
}

void handle_octal_escape(char* buffer, char* yytext) {
    char dig[2];
    char *a;
    dig[0] = (char)strtol(yytext+1, &a, 8);
    dig[1] = '\0';
    strcat(buffer, dig);
}

void finish_char(char* buffer, int line) {
    if(strlen(buffer) != 1) {
        printf("ERROR! char length != 1 in row: %d\n", line);
    } else {
        printf("Found Char literal: %s\n", buffer);
    }
}

void strip_underscores(char* buf, const char* src) {
    char* d = buf;
    for (const char* s = src; *s; s++) {
        if (*s != '_')
            *d++ = *s;
    }
    *d = '\0';
}

long parse_binary(const char* yytext) {
    for (int i = 2; yytext[i] != '\0'; i++) {
        if (yytext[i] != '0' && yytext[i] != '1') {
            fprintf(stderr, "Error: Invalid binary digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext + 2, NULL, 2);
}

long parse_octal(const char* yytext) {
    for (int i = 1; yytext[i] != '\0'; i++) {
        if (yytext[i] < '0' || yytext[i] > '7') {
            fprintf(stderr, "Error: Invalid octal digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext, NULL, 8);
}

long parse_hexadecimal(const char* yytext) {
    for (int i = 2; yytext[i] != '\0'; i++) {
        if (!isxdigit(yytext[i])) {
            fprintf(stderr, "Error: Invalid hex digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext + 2, NULL, 16);
}

long parse_decimal(const char* yytext) {
    for (int i = 0; yytext[i] != '\0'; i++) {
        if (!isdigit(yytext[i])) {
            fprintf(stderr, "Error: Invalid digit '%c' in '%s'\n", yytext[i], yytext);
            return 0;
        }
    }
    return strtol(yytext, NULL, 10);
}

int get_int(const char* yytext) {
    char clean[64];
    strip_underscores(clean, yytext);
    long val;

    if (strncmp(clean, "0b", 2) == 0 || strncmp(clean, "0B", 2) == 0) {
        val = parse_binary(clean);
    }
    else if (strncmp(clean, "0x", 2) == 0 || strncmp(clean, "0X", 2) == 0) {
        val = parse_hexadecimal(clean);
    }
    else if (clean[0] == '0') {
        val = parse_octal(clean);
    }
    else val = parse_decimal(clean);

    if (val > INT_MAX) {
        printf("Warning: Number exceeds int range, truncated to INT_MAX.\n");
        return INT_MAX;
    }

    return (int)val;
}

float get_float(const char* yytext) {
    char clean[64];
    strip_underscores(clean, yytext);
    errno = 0;
    char* endptr;
    float val = strtof(clean, &endptr);

    if ((errno == ERANGE && val == HUGE_VALF) || val > FLT_MAX) {
        printf("Warning: Float value exceeds range, truncated to FLT_MAX.\n");
        return FLT_MAX;
    }

    return val;
}

int main(int argc, char* argv[]) {
    FILE *input_file = NULL;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input_file.d>\n", argv[0]);
        return 1;
    }

    input_file = fopen(argv[1], "r");
    if (!input_file) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", argv[1]);
        return 1;
    }

    yyin = input_file;
    BEGIN(FIRST_PASS);
    
    while (yylex() != 0) {}

    fclose(input_file);
    print_class_table();
    
    input_file = fopen(argv[1], "r");
    if (!input_file) {
        fprintf(stderr, "Error: Cannot open file '%s' for second pass\n", argv[1]);
        return 1;
    }

    yyin = input_file;
    BEGIN(INITIAL);
    yyrestart(yyin);
    
    while (yylex() != 0) {}

    fclose(input_file);
    
    return 0;
}
