#ifndef JVM__METHOD_H
#define JVM__METHOD_H

#include "attribute-code.h"
#include "constant-utf-8-info.h"

namespace jvm
{
    class Method final : public ClassFileElement<Class>
    {
        friend Class;
    public:
        enum AccessFlag
        {
            ACC_PUBLIC = 0x0001, ///< Declared public; may be accessed from outside its package.
            ACC_PRIVATE = 0x0002,
            ///< Declared private; accessible only within the defining class and other classes belonging to the same nest.
            ACC_PROTECTED = 0x0004, ///< Declared protected; may be accessed within subclasses.
            ACC_STATIC = 0x0008, ///< Declared static.
            ACC_FINAL = 0x0010, ///< Declared final; must not be overridden (§5.4.5).
            ACC_SYNCHRONIZED = 0x0020, ///< Declared synchronized; invocation is wrapped by a monitor use.
            ACC_BRIDGE = 0x0040, ///< A bridge method, generated by the compiler.
            ACC_VARARGS = 0x0080, ///< Declared with variable number of arguments.
            ACC_NATIVE = 0x0100,
            ///< Declared native; implemented in a language other than the Java programming language.
            ACC_ABSTRACT = 0x0400, ///< Declared abstract; no implementation is provided.
            ACC_STRICT = 0x0800, ///< Declared strictfp; floating-point mode is FP-strict.
            ACC_SYNTHETIC = 0x1000, ///< Declared synthetic; not present in the source code.
        };

        /**
         * Add access flag to method.
         * @param flag Access flag.
         */
        void addFlag(AccessFlag flag);

        /**
         * Remove access flag from method.
         * @param flag Access flag.
         */
        void removeFlag(AccessFlag flag);

        /**
         * Add attribute to method.
         * @param attribute Method attribute.
         */
        void addAttribute(Attribute* attribute);

        /**
         * Remove attribute from filed.
         * @param attribute Method attribute.
         */
        void removeAttribute(Attribute* attribute);

        /**
         * @return Access flags set.
         */
        [[nodiscard]] const std::set<AccessFlag>* getAccessFlags() const;

        /**
         * @return Constant of field name.
         */
        [[nodiscard]] ConstantUtf8Info* getName() const;

        /**
         * @return Constant of filed descriptor.
         */
        [[nodiscard]] ConstantUtf8Info* getDescriptor() const;

        /**
         * @return Filed attributes set.
         */
        [[nodiscard]] const std::set<Attribute*>* getAttributes() const;

        /**
         * @brief Get code attribute object.
         *
         * In first call create @ref AttributeCode for this method.
         *
         * @return Code attribute for this method.
         */
        AttributeCode* getCodeAttribute();

    protected:
        void writeTo(std::ostream& os) const override;

        [[nodiscard]] std::size_t getByteSize() const override;

    private:
        /**
         * @brief Constructs a method with the specified name and descriptor.
         *
         * This constructor is intentionally not part of the public API. Instances of @ref Method are owned by a
         * @ref Class and are registered in the owning class upon creation. Therefore, only @ref Class is allowed
         * to construct @ref Method objects. To create instances of this class, use @ref Class::getOrCreateMethod.
         *
         * @param name Pointer to a UTF-8 constant containing the method name.
         * @param descriptor Pointer to a UTF-8 constant containing the method descriptor.
         *
         * @note The provided constants must have the same class owner.
         * @see Class::getOrCreateMethod
         */
        Method(ConstantUtf8Info* name, ConstantUtf8Info* descriptor);

        /**
         * @brief Validate method access flags according to the JVM specification.
         *
         * Checks that the given set of access flags represents a valid combination
         * for a JVM method. This function enforces semantic constraints defined by
         * the Java Virtual Machine Specification, including but not limited to:
         *
         * - At most one of {@c ACC_PUBLIC}, {@c ACC_PRIVATE}, {@c ACC_PROTECTED}
         *   may be present.
         * - {@c ACC_ABSTRACT} must not be combined with:
         *   {@c ACC_FINAL}, {@c ACC_NATIVE}, {@c ACC_SYNCHRONIZED},
         *   or a {@c Code} attribute.
         * - {@c ACC_NATIVE} and {@c ACC_ABSTRACT} must not both be present.
         * - {@c ACC_BRIDGE} implies {@c ACC_SYNTHETIC}.
         * - {@c ACC_STRICT} is only meaningful for non-abstract, non-native methods.
         *
         * If the flag combination is invalid, this function throws
         * {@c std::logic_error}.
         *
         * @param flags Bitmask of method access flags to validate.
         *
         * @throws std::logic_error If the flag combination violates JVM constraints.
         *
         * @note This function is called internally when modifying method access flags
         *       and before serializing the method into a class file.
         *
         * @see Method::addFlag
         * @see Method::removeFlag
         */
        static void validateFlags(uint16_t flags);

        std::set<AccessFlag> accessFlags_{}; ///< Access flags.
        ConstantUtf8Info* name_ = nullptr; ///< String constant with method name.
        ConstantUtf8Info* descriptor_ = nullptr; ///< String constant with method descriptor.
        std::set<Attribute*> attributes_{}; ///< Attributes.
        AttributeCode* codeAttribute_ = nullptr; ///< Pointer to code attribute.
    };
} // jvm

#endif //JVM__METHOD_H
