#ifndef JVM__JAVA_INTERNAL_PATHS_H_IN_H
#define JVM__JAVA_INTERNAL_PATHS_H_IN_H

#define JAVA_INTERNAL_BUILD_DIR "@JAVA_INTERNAL_BUILD_DIR@"

#define JAVA_INTERNAL_JAR "@JAVA_INTERNAL_JAR@"

#endif //JVM__JAVA_INTERNAL_PATHS_H_IN_H
